### ISSUE TITLE
Documentation: Meta & Rest

### ISSUE THREAD

**Issue by nananananate** [icssc-projects/peterportal-public-api#13]
## Meta

- [ ] Documentation on running the documentation site locally (via mkdocs)
- [ ] Resources for styling via Material for MkDocs

## Rest

- [ ] Adding more to the `REST/start-here` page. (Resources on how to test API, like via postman)
- [ ] Reordering navigation via `mkdocs.yml`
